<div class="container">
    <h2 class="tag_page_title"><?php echo $wo['lang']['livesmart_dashboard']; ?></h2>
    <div class="page-margin wow_content wow_sett_content tag_blog_cats_coll">
        <div class="valign wo_page_hdng" data-toggle="collapse" data-target="#collapseCAT" aria-expanded="true" aria-controls="collapseCAT">
            <span><svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="20" viewBox="0 0 76 76"  style="enable-background:new 0 0 76 76;" xml:space="preserve" fill="currentColor"> <g id="_x37_7_Essential_Icons_72_"><path id="Video_Camera" d="M72.9,14.4L56,25.3V22c0-4.4-3.6-8-8-8H8c-4.4,0-8,3.6-8,8v32c0,4.4,3.6,8,8,8h40c4.4,0,8-3.6,8-8v-3.3 		l16.9,10.9c1.9,1,3.1-0.7,3.1-1.7V16C76,15,74.9,13.2,72.9,14.4z M52,54c0,2.2-1.8,4-4,4H8c-2.2,0-4-1.8-4-4V22c0-2.2,1.8-4,4-4h40 		c2.2,0,4,1.8,4,4V54z M72,56.3L56,46V30l16-10.3V56.3z"/></g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g></svg></span><?php echo $wo['lang']['livesmart_dashboard']; ?>
        </div>

    </div>
    <div class="page-margin wow_content wow_sett_content">

        <div id="recent-blogs" class="row">
            <iframe src="<?php echo $wo['config']['livesmart_url'] ?>dash/integration.php?wplogin=<?php echo $wo['user']['username']; ?>&url=<?php echo base64_encode($wo['config']['livesmart_url']); ?>" style="background-color:#ffffff; padding: 0; margin:0" width="100%" height="600" ></iframe>
            <br/>
            <a href="<?php echo $wo['config']['livesmart_url'] ?>dash/" target="_blank"><?php echo $wo['lang']['livesmart_dashboard']; ?></a>
        </div>

    </div>
</div>
